### PR TITLE
add hidaya-theme to docs

### PR DESCRIPTION
**Pull request by Stunkymonkey**
not sure if you want to merge this immediately

### CODE REVIEW

**Comment by bugwelle** [comment]
Thanks! I like the theme. I'll wait for MediaElch to use the new metadata repository first, though. :-)

**Comment by Stunkymonkey** [comment]
theme is now in the metadata repo: https://github.com/mediaelch/mediaelch-meta/pull/2

**Comment by bugwelle** [comment]
Please minimize your images using https://trimage.org/ or https://imageoptim.com/mac . It saves about 30% of the binary size (tested with ImageOptim). Everything else looks fine. 👍

**Comment by Stunkymonkey** [comment]
the images are now compressed using `trimage`

**Comment by bugwelle** [comment]
Great! 70% improvement. Thank you!

**Comment by bugwelle** [comment]
https://mediaelch.github.io/mediaelch-doc/export/themes.html#id1

**Pull request merged**
